### PR TITLE
Issue #7 and #8 resolved.

### PR DESCRIPTION
**Pull request by gaurav19063**
Changing ast module to json module, resolves issue #8 and #7 ValueError: malformed node or string: <_ast.Name object at 0x000002321E54E2C8> error.

### CODE REVIEW

**Comment by gaurav19063** [comment]
I have changed the zomatopy.py module and changed ast module to json. That fixes ast string malformed error and works normally.

**Comment by gaurav19063** [comment]
I reopened this PR, Previously it was closed by mistake.

**Comment by sharadbhat** [comment]
Hi, sorry for reviewing this so late. I've been quite busy. I've taken a look at the changes, everything looks good to me. I'll approve and merge this shortly.

Thanks for opening a PR for this fix!

**Comment by gaurav19063** [comment]
Sure Sharad takes your time.

**Review by sharadbhat — APPROVED** [review]
LGTM.

**Pull request merged**
